var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/organization/chart/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__c1c0bdad._.js")
R.c("server/chunks/ssr/admin_427a6784._.js")
R.c("server/chunks/ssr/admin_1a64d3c6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ff53cd84._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5f1b759b._.js")
R.c("server/chunks/ssr/dc982_next_dist_dc6fd238._.js")
R.c("server/chunks/ssr/admin_app_3b46025c._.js")
R.c("server/chunks/ssr/dc982_next_dist_client_components_builtin_global-error_adf7df43.js")
R.c("server/chunks/ssr/admin_40a6f4bd._.js")
R.c("server/chunks/ssr/dc982_next_dist_client_components_96404d87._.js")
R.c("server/chunks/ssr/dc982_next_dist_client_components_builtin_forbidden_067d55bc.js")
R.c("server/chunks/ssr/dc982_next_dist_client_components_builtin_unauthorized_0a35dd7c.js")
R.c("server/chunks/ssr/admin_26cb33eb._.js")
R.c("server/chunks/ssr/c084d__next-internal_server_app_(dashboard)_organization_chart_page_actions_bc5fa7b9.js")
R.m(626317)
module.exports=R.m(626317).exports
