// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admins" | "/admins/add" | "/admins/create" | "/admins/request" | "/ads" | "/agencies" | "/agencies/add" | "/agencies/create" | "/agencies/request" | "/agency" | "/ai/automation" | "/ai/insights" | "/analytics/live-map" | "/api-center" | "/apply" | "/apply/admin" | "/apply/agency" | "/apply/customer-service" | "/apply/host" | "/apply/operator" | "/apply/seller" | "/apply/super-admin" | "/apply/team-leader" | "/banners" | "/bans/device" | "/bans/id" | "/calls" | "/change-password" | "/cms" | "/compliance" | "/customer-service" | "/customer-support" | "/customer-support/add" | "/customer-support/create" | "/customer-support/list" | "/customer-support/request" | "/dashboard" | "/deletions" | "/employees" | "/events" | "/finance/ledger" | "/health" | "/help-support" | "/host-levels" | "/host-management" | "/hosts" | "/hosts/add" | "/hosts/create" | "/hosts/request" | "/kyc" | "/login" | "/login/[role]" | "/logout" | "/logs" | "/messages/activity" | "/messages/system" | "/moderation" | "/operator" | "/operators" | "/operators/create" | "/operators/request" | "/organization/branches" | "/organization/chart" | "/organization/departments" | "/organization/teams" | "/owner" | "/profile" | "/recharges/seller" | "/recharges/user" | "/referrals" | "/referrals/links" | "/reports" | "/rooms" | "/security" | "/security/compare" | "/security/logs" | "/security/permissions" | "/security/templates" | "/sellers" | "/sellers/add" | "/sellers/create" | "/sellers/request" | "/settings" | "/settings/automations" | "/settings/form-builder" | "/settings/marketplace" | "/settings/plugins" | "/settings/referral" | "/settings/workflows" | "/settings/workflows/canvas" | "/super-admin" | "/super-admins" | "/super-admins/create" | "/super-admins/request" | "/tasks" | "/users" | "/users/[id]" | "/users/add" | "/users/history/[userId]" | "/users/new" | "/verification" | "/verification/requests" | "/vip" | "/withdrawals"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admins": {}
  "/admins/add": {}
  "/admins/create": {}
  "/admins/request": {}
  "/ads": {}
  "/agencies": {}
  "/agencies/add": {}
  "/agencies/create": {}
  "/agencies/request": {}
  "/agency": {}
  "/ai/automation": {}
  "/ai/insights": {}
  "/analytics/live-map": {}
  "/api-center": {}
  "/apply": {}
  "/apply/admin": {}
  "/apply/agency": {}
  "/apply/customer-service": {}
  "/apply/host": {}
  "/apply/operator": {}
  "/apply/seller": {}
  "/apply/super-admin": {}
  "/apply/team-leader": {}
  "/banners": {}
  "/bans/device": {}
  "/bans/id": {}
  "/calls": {}
  "/change-password": {}
  "/cms": {}
  "/compliance": {}
  "/customer-service": {}
  "/customer-support": {}
  "/customer-support/add": {}
  "/customer-support/create": {}
  "/customer-support/list": {}
  "/customer-support/request": {}
  "/dashboard": {}
  "/deletions": {}
  "/employees": {}
  "/events": {}
  "/finance/ledger": {}
  "/health": {}
  "/help-support": {}
  "/host-levels": {}
  "/host-management": {}
  "/hosts": {}
  "/hosts/add": {}
  "/hosts/create": {}
  "/hosts/request": {}
  "/kyc": {}
  "/login": {}
  "/login/[role]": { "role": string; }
  "/logout": {}
  "/logs": {}
  "/messages/activity": {}
  "/messages/system": {}
  "/moderation": {}
  "/operator": {}
  "/operators": {}
  "/operators/create": {}
  "/operators/request": {}
  "/organization/branches": {}
  "/organization/chart": {}
  "/organization/departments": {}
  "/organization/teams": {}
  "/owner": {}
  "/profile": {}
  "/recharges/seller": {}
  "/recharges/user": {}
  "/referrals": {}
  "/referrals/links": {}
  "/reports": {}
  "/rooms": {}
  "/security": {}
  "/security/compare": {}
  "/security/logs": {}
  "/security/permissions": {}
  "/security/templates": {}
  "/sellers": {}
  "/sellers/add": {}
  "/sellers/create": {}
  "/sellers/request": {}
  "/settings": {}
  "/settings/automations": {}
  "/settings/form-builder": {}
  "/settings/marketplace": {}
  "/settings/plugins": {}
  "/settings/referral": {}
  "/settings/workflows": {}
  "/settings/workflows/canvas": {}
  "/super-admin": {}
  "/super-admins": {}
  "/super-admins/create": {}
  "/super-admins/request": {}
  "/tasks": {}
  "/users": {}
  "/users/[id]": { "id": string; }
  "/users/add": {}
  "/users/history/[userId]": { "userId": string; }
  "/users/new": {}
  "/verification": {}
  "/verification/requests": {}
  "/vip": {}
  "/withdrawals": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
