// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/(admin)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/(admin)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(agency)/agency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agency">> = Specific
  const handler = {} as typeof import("../../app/(agency)/agency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/login/[role]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login/[role]">> = Specific
  const handler = {} as typeof import("../../app/(auth)/login/[role]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth)/logout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logout">> = Specific
  const handler = {} as typeof import("../../app/(auth)/logout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(customer-service)/customer-service/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer-service">> = Specific
  const handler = {} as typeof import("../../app/(customer-service)/customer-service/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/admins/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admins/add">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/admins/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/admins/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admins/create">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/admins/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/admins/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admins">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/admins/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/admins/request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admins/request">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/admins/request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/ads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ads">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/ads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/agencies/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agencies/add">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/agencies/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/agencies/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agencies/create">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/agencies/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/agencies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agencies">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/agencies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/agencies/request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agencies/request">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/agencies/request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/ai/automation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai/automation">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/ai/automation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/ai/insights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai/insights">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/ai/insights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/analytics/live-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/live-map">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/analytics/live-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/api-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/api-center">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/api-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/banners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/banners">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/banners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/bans/device/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bans/device">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/bans/device/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/bans/id/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bans/id">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/bans/id/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/calls/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calls">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/calls/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/cms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cms">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/cms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/compliance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/compliance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/customer-support/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer-support/add">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/customer-support/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/customer-support/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer-support/create">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/customer-support/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/customer-support/list/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer-support/list">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/customer-support/list/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/customer-support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer-support">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/customer-support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/customer-support/request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer-support/request">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/customer-support/request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/deletions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/deletions">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/deletions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/finance/ledger/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/ledger">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/finance/ledger/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/health">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/help-support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/help-support">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/help-support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/host-levels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/host-levels">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/host-levels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/host-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/host-management">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/host-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/hosts/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hosts/add">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/hosts/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/hosts/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hosts/create">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/hosts/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/hosts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hosts">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/hosts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/hosts/request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hosts/request">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/hosts/request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/kyc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kyc">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/kyc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logs">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/messages/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/messages/activity">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/messages/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/messages/system/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/messages/system">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/messages/system/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/moderation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/moderation">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/moderation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/operators/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operators/create">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/operators/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/operators/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operators">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/operators/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/operators/request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operators/request">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/operators/request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/organization/branches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organization/branches">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/organization/branches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/organization/chart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organization/chart">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/organization/chart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/organization/departments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organization/departments">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/organization/departments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/organization/teams/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organization/teams">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/organization/teams/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/recharges/seller/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recharges/seller">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/recharges/seller/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/recharges/user/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recharges/user">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/recharges/user/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/referrals/links/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referrals/links">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/referrals/links/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/referrals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referrals">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/referrals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/rooms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rooms">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/rooms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/security/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security/compare">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/security/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/security/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security/logs">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/security/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/security/permissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security/permissions">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/security/permissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/security/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security/templates">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/security/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/sellers/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sellers/add">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/sellers/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/sellers/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sellers/create">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/sellers/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/sellers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sellers">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/sellers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/sellers/request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sellers/request">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/sellers/request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/settings/automations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/automations">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/settings/automations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/settings/form-builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/form-builder">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/settings/form-builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/settings/marketplace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/marketplace">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/settings/marketplace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/settings/plugins/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/plugins">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/settings/plugins/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/settings/referral/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/referral">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/settings/referral/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/settings/workflows/canvas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/workflows/canvas">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/settings/workflows/canvas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/settings/workflows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/workflows">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/settings/workflows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/super-admins/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admins/create">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/super-admins/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/super-admins/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admins">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/super-admins/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/super-admins/request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admins/request">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/super-admins/request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/users/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/users/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/users/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users/add">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/users/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/users/history/[userId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users/history/[userId]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/users/history/[userId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/users/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users/new">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/users/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verification">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/verification/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verification/requests">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/verification/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/vip/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vip">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/vip/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/withdrawals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/withdrawals">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/withdrawals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(operator)/operator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operator">> = Specific
  const handler = {} as typeof import("../../app/(operator)/operator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(owner)/owner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner">> = Specific
  const handler = {} as typeof import("../../app/(owner)/owner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(super-admin)/super-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin">> = Specific
  const handler = {} as typeof import("../../app/(super-admin)/super-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/apply/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apply/admin">> = Specific
  const handler = {} as typeof import("../../app/apply/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/apply/agency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apply/agency">> = Specific
  const handler = {} as typeof import("../../app/apply/agency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/apply/customer-service/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apply/customer-service">> = Specific
  const handler = {} as typeof import("../../app/apply/customer-service/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/apply/host/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apply/host">> = Specific
  const handler = {} as typeof import("../../app/apply/host/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/apply/operator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apply/operator">> = Specific
  const handler = {} as typeof import("../../app/apply/operator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/apply/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apply">> = Specific
  const handler = {} as typeof import("../../app/apply/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/apply/seller/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apply/seller">> = Specific
  const handler = {} as typeof import("../../app/apply/seller/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/apply/super-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apply/super-admin">> = Specific
  const handler = {} as typeof import("../../app/apply/super-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/apply/team-leader/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apply/team-leader">> = Specific
  const handler = {} as typeof import("../../app/apply/team-leader/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/change-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/change-password">> = Specific
  const handler = {} as typeof import("../../app/change-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/(admin)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(admin)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(agency)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(agency)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(customer-service)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(customer-service)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(operator)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(operator)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(owner)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(owner)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(super-admin)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(super-admin)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
