var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/security/compare/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__e3bb95c5._.js")
R.c("server/chunks/ssr/admin_427a6784._.js")
R.c("server/chunks/ssr/admin_392f5e9f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ff53cd84._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5f1b759b._.js")
R.c("server/chunks/ssr/dc982_next_dist_dc6fd238._.js")
R.c("server/chunks/ssr/admin_app_3b46025c._.js")
R.c("server/chunks/ssr/dc982_next_dist_client_components_builtin_global-error_adf7df43.js")
R.c("server/chunks/ssr/admin_40a6f4bd._.js")
R.c("server/chunks/ssr/dc982_next_dist_client_components_96404d87._.js")
R.c("server/chunks/ssr/dc982_next_dist_client_components_builtin_forbidden_067d55bc.js")
R.c("server/chunks/ssr/dc982_next_dist_client_components_builtin_unauthorized_0a35dd7c.js")
R.c("server/chunks/ssr/admin_26cb33eb._.js")
R.c("server/chunks/ssr/c084d__next-internal_server_app_(dashboard)_security_compare_page_actions_03626a13.js")
R.m(799488)
module.exports=R.m(799488).exports
