var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(admin)/admin/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__412b600d._.js")
R.c("server/chunks/ssr/admin_427a6784._.js")
R.c("server/chunks/ssr/admin_5aa0a908._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ff53cd84._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5f1b759b._.js")
R.c("server/chunks/ssr/dc982_next_dist_dc6fd238._.js")
R.c("server/chunks/ssr/admin_app_3b46025c._.js")
R.c("server/chunks/ssr/dc982_next_dist_client_components_builtin_global-error_adf7df43.js")
R.c("server/chunks/ssr/admin_40a6f4bd._.js")
R.c("server/chunks/ssr/dc982_next_dist_client_components_96404d87._.js")
R.c("server/chunks/ssr/dc982_next_dist_client_components_builtin_forbidden_067d55bc.js")
R.c("server/chunks/ssr/dc982_next_dist_client_components_builtin_unauthorized_0a35dd7c.js")
R.c("server/chunks/ssr/admin_app_(admin)_layout_tsx_e48c7945._.js")
R.c("server/chunks/ssr/admin__next-internal_server_app_(admin)_admin_page_actions_3cc3147c.js")
R.m(898104)
module.exports=R.m(898104).exports
